const COLOR_LIBRARY = {
  spring: {
    trueColor: [
      { name: "Light Red", hex: "#f87271" },
      { name: "Rusty Red", hex: "#dd3848" },
      { name: "Coffee", hex: "#6f4f36" },
      { name: "Jasmine", hex: "#f9de85" },
      { name: "Apple Green", hex: "#b5bf4f" },
      { name: "Indigo Dye", hex: "#1e4377" },
      { name: "Powder Blue", hex: "#a3bbe1" },
      { name: "Dutch White", hex: "#f4e1c1" },
      { name: "Van Dyke", hex: "#41342b" },
      { name: "Earth Yellow", hex: "#efad56" }
    ],
    saturation4: [
      { name: "Light Red S4", hex: "#F78C8C" },
      { name: "Rusty Red S4", hex: "#DE5966" },
      { name: "Coffee S4", hex: "#705642" },
      { name: "Jasmine S4", hex: "#FAE49C" },
      { name: "Apple Green S4", hex: "#B8BF65" },
      { name: "Indigo Dye S4", hex: "#304E78" },
      { name: "Powder Blue S4", hex: "#AEC1E0" },
      { name: "Dutch White S4", hex: "#F5E6CC" },
      { name: "Van Dyke S4", hex: "#40362E" },
      { name: "Earth Yellow S4", hex: "#efad56" }
    ],
    saturation3: [
      { name: "Light Red S3", hex: "f7a7a7" },
      { name: "Rusty Red S3", hex: "#DE7A84" },
      { name: "Coffee S3", hex: "#705D4E" },
      { name: "Jasmine S3", hex: "#FAE9B3" },
      { name: "Apple Green S3", hex: "#BABF7C" },
      { name: "Indigo Dye S3", hex: "#425878" },
      { name: "Powder Blue S3", hex: "#BBC9E0" },
      { name: "Dutch White S3", hex: "#F5E9D6" },
      { name: "Van Dyke S3", hex: "#403833" },
      { name: "Earth Yellow S3", hex: "#efad56" }
    ],
    saturation2: [
      { name: "Light Red S2", hex: "#f7c2c2" },
      { name: "Rusty Red S2", hex: "#DE9BA2" },
      { name: "Coffee S2", hex: "#706359" },
      { name: "Jasmine S2", hex: "#FAEFCB" },
      { name: "Apple Green S2", hex: "#BBBF92" },
      { name: "Indigo Dye S2", hex: "#546378" },
      { name: "Powder Blue S2", hex: "#C7D1E0" },
      { name: "Dutch White S2", hex: "#F5EDE0" },
      { name: "Van Dyke S2", hex: "#403B37" },
      { name: "Earth Yellow S2", hex: "#efad56" }
    ],
    saturation1: [
      { name: "Light Red S1", hex: "#f7dddd" },
      { name: "Rusty Red S1", hex: "#DEBDC0" },
      { name: "Coffee S1", hex: "#706A65" },
      { name: "Jasmine S1", hex: "#FAF4E2" },
      { name: "Apple Green S1", hex: "#BDBFA9" },
      { name: "Indigo Dye S1", hex: "#666D78" },
      { name: "Powder Blue S1", hex: "#D4D9E0" },
      { name: "Dutch White S1", hex: "#F5F1EB" },
      { name: "Van Dyke S1", hex: "#403D3B" },
      { name: "Earth Yellow S1", hex: "#404040" }
    ],
    neutral: [
      { name: "Light Red N", hex: "#f7f7f7" },
      { name: "Rusty Red N", hex: "#DEDEDE" },
      { name: "Coffee N", hex: "#707070" },
      { name: "Jasmine N", hex: "#FAFAFA" },
      { name: "Apple Green N", hex: "#BFBFBF" },
      { name: "Indigo Dye N", hex: "#787878" },
      { name: "Powder Blue N", hex: "#E0E0E0" },
      { name: "Dutch White N", hex: "#F5F5F5" },
      { name: "Van Dyke N", hex: "#B8A8A0" },
      { name: "Earth Yellow N", hex: "#B8B0B8" }
    ],
    value4: [
      { name: "Light Red V4", hex: "#c55b5b" },
      { name: "Rusty Red V4", hex: "#c53240" },
      { name: "Coffee V4", hex: "#c58c60" },
      { name: "Jasmine V4", hex: "#c5b069" },
      { name: "Apple Green V4", hex: "#bbc551" },
      { name: "Indigo Dye V4", hex: "#316fc5" },
      { name: "Powder Blue V4", hex: "#8fa4c5" },
      { name: "Dutch White V4", hex: "#c5b69c" },
      { name: "Van Dyke V4", hex: "#c59e82" },
      { name: "Earth Yellow V4", hex: "#c58f47" }
    ],
    value3: [
      { name: "Light Red V3", hex: "#944444" },
      { name: "Rusty Red V3", hex: "#942530" },
      { name: "Coffee V3", hex: "#946948" },
      { name: "Jasmine V3", hex: "#94844f" },
      { name: "Apple Green V3", hex: "#8c943d" },
      { name: "Indigo Dye V3", hex: "#255394" },
      { name: "Powder Blue V3", hex: "#6b7b94" },
      { name: "Dutch White V3", hex: "#948875" },
      { name: "Van Dyke V3", hex: "#947662" },
      { name: "Earth Yellow V3", hex: "#946b35" }
    ],
    value2: [
      { name: "Light Red V2", hex: "#622d2d" },
      { name: "Rusty Red V2", hex: "#621920" },
      { name: "Coffee V2", hex: "#624630" },
      { name: "Jasmine V2", hex: "#625834" },
      { name: "Apple Green V2", hex: "#5d6228" },
      { name: "Indigo Dye V2", hex: "#183762" },
      { name: "Powder Blue V2", hex: "#475262" },
      { name: "Dutch White V2", hex: "#625b4e" },
      { name: "Van Dyke V2", hex: "#624f41" },
      { name: "Earth Yellow V2", hex: "#624723" }
    ],
    value1: [
      { name: "Light Red V1", hex: "#311616" },
      { name: "Rusty Red V1", hex: "#310c10" },
      { name: "Coffee V1", hex: "#312318" },
      { name: "Jasmine V1", hex: "#312c1a" },
      { name: "Apple Green V1", hex: "#2e3114" },
      { name: "Indigo Dye V1", hex: "#0c1b31" },
      { name: "Powder Blue V1", hex: "#232931" },
      { name: "Dutch White V1", hex: "#312d27" },
      { name: "Van Dyke V1", hex: "#312720" },
      { name: "Earth Yellow V1", hex: "#312311" }
    ],
    value0: [
      { name: "Light Red B", hex: "#180b0b" },
      { name: "Rusty Red B", hex: "#180608" },
      { name: "Coffee B", hex: "#18110c" },
      { name: "Jasmine B", hex: "#18160d" },
      { name: "Apple Green B", hex: "#17180a" },
      { name: "Indigo Dye B", hex: "#060d18" },
      { name: "Powder Blue B", hex: "#111418" },
      { name: "Dutch White B", hex: "#181613" },
      { name: "Van Dyke B", hex: "#181310" },
      { name: "Earth Yellow B", hex: "#181108" }
    ],
  },
  summer: {
    trueColor: [
      { name: "Rose Pompadour", hex: "#ea748e" },
      { name: "Raspberry Rose", hex: "#bb4869" },
      { name: "Silver", hex: "#b6acab" },
      { name: "Cambridge Blue", hex: "#7fbb9f" },
      { name: "Pine Green", hex: "#236c63" },
      { name: "Cerulean", hex: "#1f6780" },
      { name: "Davy's Gray", hex: "#48464b" },
      { name: "Timberwolf", hex: "#d4ccc1" },
      { name: "Glaucous", hex: "#7c82bc" },
      { name: "Moonstone", hex: "#5db0ce" }
    ],
    saturation4: [
      { name: "Rose Pompadou S4", hex: "#ea345c" },
      { name: "Raspberry Rose S4", hex: "#bb2953" },
      { name: "Silver S4", hex: "#b63528" },
      { name: "Cambridge Blue S4", hex: "#29bb77" },
      { name: "Pine Green S4", hex: "#186c61" },
      { name: "Cerulean S4", hex: "#1c6680" },
      { name: "Davy's Gray S4", hex: "#28104b" },
      { name: "Timberwolf S4", hex: "#d48e2f" },
      { name: "Glaucous S4", hex: "#2a37bc" },
      { name: "Moonstone S4", hex: "#2ea3ce" }
    ],
    saturation3: [
      { name: "Rose Pompadour S3", hex: "#ea617f" },
      { name: "Raspberry Rose S3", hex: "#bb4e6d" },
      { name: "Silver S3", hex: "#b6554c" },
      { name: "Cambridge Blue S3", hex: "#4ebb88" },
      { name: "Pine Green S3", hex: "#2d6c64" },
      { name: "Cerulean S3", hex: "#356c80" },
      { name: "Davy's Gray S3", hex: "#301f4b" },
      { name: "Timberwolf S3", hex: "#d4a058" },
      { name: "Glaucous S3", hex: "#4e58bc" },
      { name: "Moonstone S3", hex: "#56aece" }
    ],
    saturation2: [
      { name: "Rose Pompadour S2", hex: "#ea8fa3" },
      { name: "Raspberry Rose S2", hex: "#bb7287" },
      { name: "Silver S2", hex: "#b6756f" },
      { name: "Cambridge Blue S2", hex: "#72bb99" },
      { name: "Pine Green S2", hex: "#426c66" },
      { name: "Cerulean S2", hex: "#4e7380" },
      { name: "Davy's Gray S2", hex: "#392d4b" },
      { name: "Timberwolf S2", hex: "#d4b181" },
      { name: "Glaucous S2", hex: "#7379bc" },
      { name: "Moonstone S2", hex: "#7eb8ce" }
    ],
    saturation1: [
      { name: "Rose Pompadour S1", hex: "#eabcc6" },
      { name: "Raspberry Rose S1", hex: "#bb96a1" },
      { name: "Silver S1", hex: "#b69592" },
      { name: "Cambridge Blue S1", hex: "#96bbaa" },
      { name: "Pine Green S1", hex: "#576c69" },
      { name: "Cerulean S1", hex: "#677980" },
      { name: "Davy's Gray S1", hex: "#423c4b" },
      { name: "Timberwolf S1", hex: "#d4c2aa" },
      { name: "Glaucous S1", hex: "#979abc" },
      { name: "Moonstone S1", hex: "#a6c3ce" }
    ],
    neutral: [
      { name: "Rose Pompadour N", hex: "#eaeaea" },
      { name: "Raspberry Rose ", hex: "#bbbbbb" },
      { name: "Silver N", hex: "#b6b6b6" },
      { name: "Cambridge Blue N", hex: "#bbbbbb" },
      { name: "Pine Green N", hex: "#6c6c6c" },
      { name: "Cerulean N", hex: "#808080" },
      { name: "Davy's Gray N", hex: "#4b4b4b" },
      { name: "Timberwolf N", hex: "#d4d4d4" },
      { name: "Glaucous N", hex: "#bcbcbc" },
      { name: "Moonstone N", hex: "#cecece" }
    ],
    value4: [
      { name: "Rose Pompadour V4", hex: "#c56278" },
      { name: "Raspberry Rose V4", hex: "#c54c6f" },
      { name: "Silver V4", hex: "#c5bbb9" },
      { name: "Cambridge Blue V4", hex: "#86c5a8" },
      { name: "Pine Green V4", hex: "#40c5b5" },
      { name: "Cerulean V4", hex: "#2f9fc5" },
      { name: "Davy's Gray V4", hex: "#bdb8c5" },
      { name: "Timberwolf V4", hex: "#c5beb4" },
      { name: "Glaucous V4", hex: "#8288c5" },
      { name: "Moonstone V4", hex: "#59a9c5" }
    ],
    value3: [
      { name: "Rose Pompadour V3", hex: "#94495a" },
      { name: "Raspberry Rose V3", hex: "#943953" },
      { name: "Silver V3", hex: "#948c8b" },
      { name: "Cambridge Blue V3", hex: "#64947e" },
      { name: "Pine Green V3", hex: "#309488" },
      { name: "Cerulean V3", hex: "#237794" },
      { name: "Davy's Gray V3", hex: "#8e8a94" },
      { name: "Timberwolf V3", hex: "#948e87" },
      { name: "Glaucous V3", hex: "#616694" },
      { name: "Moonstone V3", hex: "#437e94" }
    ],
    value2: [
      { name: "Rose Pompadour V2", hex: "#62313c" },
      { name: "Raspberry Rose V2", hex: "#622637" },
      { name: "Silver V2", hex: "#625d5c" },
      { name: "Cambridge Blue V2", hex: "#436254" },
      { name: "Pine Green V2", hex: "#20625a" },
      { name: "Cerulean V2", hex: "#174f62" },
      { name: "Davy's Gray V2", hex: "#5e5c62" },
      { name: "Timberwolf V2", hex: "#625f5a" },
      { name: "Glaucous V2", hex: "#414462" },
      { name: "Moonstone V2", hex: "#2c5462" }
    ],
    value1: [
      { name: "Rose Pompadour V1", hex: "#31181e" },
      { name: "Raspberry Rose V1", hex: "#31131b" },
      { name: "Silver V1", hex: "#312e2e" },
      { name: "Cambridge Blue V1", hex: "#21312a" },
      { name: "Pine Green V1", hex: "#10312d" },
      { name: "Cerulean V1", hex: "#0b2731" },
      { name: "Davy's Gray V1", hex: "#2f2e31" },
      { name: "Timberwolf V1", hex: "#312f2d" },
      { name: "Glaucous V1", hex: "#202231" },
      { name: "Moonstone V1", hex: "#162a31" }
    ],
    value0: [
      { name: "Rose Pompadour B", hex: "#180c0f" },
      { name: "Raspberry Rose B", hex: "#18090d" },
      { name: "Silver B", hex: "#181717" },
      { name: "Cambridge Blue B", hex: "#101815" },
      { name: "Pine Green B", hex: "#081816" },
      { name: "Cerulean B", hex: "#051318" },
      { name: "Davy's Gray B", hex: "#171718" },
      { name: "Timberwolf B", hex: "#181716" },
      { name: "Glaucous B", hex: "#101118" },
      { name: "Moonstone B", hex: "#0b1518" }
    ],
  },
  autumn: {
    trueColor: [
      { name: "Atomic Tangerine", hex: "#F09560" },
      { name: "Cardinal", hex: "#A73340" },
      { name: "Van Dyke", hex: "#4B332F" },
      { name: "Ecru", hex: "#DEC58F" },
      { name: "Reseda Green", hex: "#80856E" },
      { name: "Buff", hex: "#DA9B7C" },
      { name: "Black Olive", hex: "#424236" },
      { name: "Khaki", hex: "#B8AFA0" },
      { name: "Eggplant", hex: "#572B38" },
      { name: "Moonstone", hex: "#5BADC5" }
    ],
    saturation4: [
      { name: "Atomic Tangerine S4", hex: "#E2996F" },
      { name: "Cardinal S4", hex: "#9C3F4A" },
      { name: "Van Dyke S4", hex: "#483532" },
      { name: "Ecru S4", hex: "#D6C399" },
      { name: "Reseda Green S4", hex: "#7F8372" },
      { name: "Buff S4", hex: "#D19E85" },
      { name: "Black Olive S4", hex: "#424238" },
      { name: "Khaki S4", hex: "#B4ADA1" },
      { name: "Eggplant S4", hex: "#512E39" },
      { name: "Moonstone S4", hex: "#64A6BA" }
    ],
    saturation3: [
      { name: "Atomic Tangerine S3", hex: "#F0B999" },
      { name: "Cardinal S3", hex: "#A66169" },
      { name: "Van Dyke S3", hex: "#4A3C3A" },
      { name: "Ecru S3", hex: "#DECFAE" },
      { name: "Reseda Green S3", hex: "#828577" },
      { name: "Buff S3", hex: "#D9B3A1" },
      { name: "Black Olive S3", hex: "#42423B" },
      { name: "Khaki S3", hex: "#B8B2A9" },
      { name: "Eggplant S3", hex: "#573C44" },
      { name: "Moonstone S3", hex: "#85B6C4" }
    ],
    saturation2: [
      { name: "Atomic Tangerine S2", hex: "#F0CBB6" },
      { name: "Cardinal S2", hex: "#A6787D" },
      { name: "Van Dyke S2", hex: "#4A413F" },
      { name: "Ecru S2", hex: "#DED4BE" },
      { name: "Reseda Green S2", hex: "#83857C" },
      { name: "Buff S3", hex: "#D9C0B3" },
      { name: "Black Olive S2", hex: "#42423E" },
      { name: "Khaki S2", hex: "#B8B4AE" },
      { name: "Eggplant S2", hex: "#57454A" },
      { name: "Moonstone S2", hex: "#9ABAC4" }
    ],
    saturation1: [
      { name: "Atomic Tangerine S1", hex: "#F0DDD3" },
      { name: "Cardinal S1", hex: "#A68F92" },
      { name: "Van Dyke S1", hex: "#4A4545" },
      { name: "Ecru S1", hex: "#DED9CE" },
      { name: "Reseda Green S1", hex: "#848580" },
      { name: "Buff S1", hex: "#D9CCC6" },
      { name: "Black Olive S1", hex: "#424240" },
      { name: "Khaki S1", hex: "#B8B6B3" },
      { name: "Eggplant S1", hex: "#574E51" },
      { name: "Moonstone S1", hex: "#AFBFC4" }
    ],
    neutral: [
      { name: "Atomic Tangerine N", hex: "#F0F0F0" },
      { name: "Cardinal N", hex: "#A6A6A6" },
      { name: "Van Dyke N", hex: "#4A4A4A" },
      { name: "Ecru N", hex: "#DEDEDE" },
      { name: "Reseda Green N", hex: "#858585" },
      { name: "Buff N", hex: "#D9D9D9" },
      { name: "Black Olive N", hex: "#424242" },
      { name: "Khaki N", hex: "#B8B8B8" },
      { name: "Eggplant N", hex: "#575757" },
      { name: "Moonstone N", hex: "#C4C4C4" }
    ],
    value4: [
      { name: "Atomic Tangerine v4", hex: "#c57a4f" },
      { name: "Cardinal V4", hex: "#c53c4b" },
      { name: "Van Dyke V4", hex: "#c5867c" },
      { name: "Ecru V4", hex: "#c5af7f" },
      { name: "Reseda Green V4", hex: "#bec5a3" },
      { name: "Buff V4", hex: "#c58c70" },
      { name: "Black Olive V4", hex: "#c5c5a1" },
      { name: "Khaki V4", hex: "#c5bcac" },
      { name: "Eggplant V4", hex: "#c5617f" },
      { name: "Moonstone V4", hex: "#5badc5" }
    ],
    value3: [
      { name: "Atomic Tangerine V3", hex: "#945c3b" },
      { name: "Cardinal V3", hex: "#942d38" },
      { name: "Van Dyke V3", hex: "#94645d" },
      { name: "Ecru V3", hex: "#94835f" },
      { name: "Reseda Green V3", hex: "#8e947a" },
      { name: "Buff V3", hex: "#946954" },
      { name: "Black Olive V3", hex: "#949479" },
      { name: "Khaki V3", hex: "#948d81" },
      { name: "Eggplant V3", hex: "#94495f" },
      { name: "Moonstone V3", hex: "#448294" }
    ],
    value2: [
      { name: "Atomic Tangerine V2", hex: "#623d27" },
      { name: "Cardinal V2", hex: "#621e25" },
      { name: "Van Dyke V2", hex: "#62433e" },
      { name: "Ecru V2", hex: "#62573f" },
      { name: "Reseda Green V2", hex: "#5f6251" },
      { name: "Buff V2", hex: "#624638" },
      { name: "Black Olive V2", hex: "#626250" },
      { name: "Khaki V2", hex: "#625e56" },
      { name: "Eggplant V2", hex: "#62303f" },
      { name: "Moonstone V2", hex: "#2d5662" }
    ],
    value1: [
      { name: "Atomic Tangerine V1", hex: "#311e13" },
      { name: "Cardinal V1", hex: "#310f12" },
      { name: "Van Dyke V1", hex: "#31211f" },
      { name: "Ecru V1", hex: "#312b1f" },
      { name: "Reseda Green V1", hex: "#2f3128" },
      { name: "Buff V1", hex: "#31231c" },
      { name: "Black Olive V1", hex: "#313128" },
      { name: "Khaki V1", hex: "#312f2b" },
      { name: "Eggplant V1", hex: "#31181f" },
      { name: "Moonstone V1", hex: "#162b31" }
    ],
    value0: [
      { name: "Atomic Tangerine B", hex: "#180f09" },
      { name: "Cardinal B", hex: "#180709" },
      { name: "Van Dyke B", hex: "#18100f" },
      { name: "Ecru B", hex: "#18150f" },
      { name: "Reseda Green B", hex: "#171814" },
      { name: "Buff B", hex: "#18110e" },
      { name: "Black Olive B", hex: "#181814" },
      { name: "Khaki B", hex: "#181715" },
      { name: "Eggplant B", hex: "#180c0f" },
      { name: "Moonstone B", hex: "#0b1518" }
    ],
    
    
  },
  winter: {
    trueColor: [
      { name: "Pink Lavender", hex: "#efc2df" },
      { name: "Magenta Dye", hex: "#b73274" },
      { name: "Van Dyke", hex: "#4e3f3a" },
      { name: "Flax", hex: "#efed98" },
      { name: "Ash Gray", hex: "#bfdcca" },
      { name: "Glaucous", hex: "#6c80bd" },
      { name: "Space Cadet", hex: "#252a48" },
      { name: "Lavender (web)", hex: "#edf0ff" },
      { name: "Dim Gray", hex: "#74706f" },
      { name: "Violet (JTC)", hex: "#6a4068" }
    ],
    saturation4: [
      { name: "Pink Lavender S4", hex: "#F0CBE3" },
      { name: "Magenta Dye S4", hex: "#B84C82" },
      { name: "Van Dyke S4", hex: "#4f433f" },
      { name: "Flax S4", hex: "#F0EFAB" },
      { name: "Ash Gray S4", hex: "#C4DBCE" },
      { name: "Glaucous S4", hex: "#7C8CBD" },
      { name: "Space Cadet S4", hex: "#2B3047" },
      { name: "Lavender (web) S4", hex: "#F1F3FF" },
      { name: "Dim Gray S4", hex: "#73706f" },
      { name: "Violet (JTC) S4", hex: "#6B4969" }
    ],
    saturation3: [
      { name: "Pink Lavender S3", hex: "#F0D4E6" },
      { name: "Magenta Dye S3", hex: "#B8678F" },
      { name: "Van Dyke S3", hex: "#4f4643" },
      { name: "Flax S3", hex: "#F0EFBC" },
      { name: "Ash Gray S3", hex: "#CADBD2" },
      { name: "Glaucous S3", hex: "#8C98BD" },
      { name: "Space Cadet S3", hex: "#323647" },
      { name: "Lavender (web) S3", hex: "#F4F6FF" },
      { name: "Dim Gray S3", hex: "S#737170" },
      { name: "Violet (JTC) S3", hex: "#6B5169" }
    ],
    saturation2: [
      { name: "Pink Lavender S2", hex: "#F0DDE9" },
      { name: "Magenta Dye S2", hex: "#B8829D" },
      { name: "Van Dyke S2", hex: "#4f497" },
      { name: "Flax S2", hex: "#F0EFCD" },
      { name: "Ash Gray S2", hex: "#D0DBD5" },
      { name: "Glaucous S2", hex: "#9CA4BD" },
      { name: "Space Cadet S2", hex: "#393C47" },
      { name: "Lavender (web) S2", hex: "#F8F9FF" },
      { name: "Dim Gray S2", hex: "#737171" },
      { name: "Violet (JTC) S2", hex: "#6B5A6A" }
    ],
    saturation1: [
      { name: "Pink Lavender S1", hex: "F0E7EC" },
      { name: "Magenta Dye S1", hex: "#B89DAA" },
      { name: "Van Dyke S1", hex: "#4f4c4b" },
      { name: "Flax S1", hex: "#F0EFDE" },
      { name: "Ash Gray S1", hex: "#D6DBD8" },
      { name: "Glaucous S1", hex: "#ACB1BD" },
      { name: "Space Cadet S1", hex: "#404247" },
      { name: "Lavender (web) S1", hex: "#FBFCFF" },
      { name: "Dim Gray S1", hex: "#737272" },
      { name: "Violet (JTC) S1", hex: "#6B636B" }
    ],
    neutral: [
      { name: "Pink Lavender N", hex: "#F0F0F0" },
      { name: "Magenta Dye N", hex: "#B8B8B8" },
      { name: "Van Dyke N", hex: "#4f4f4f" },
      { name: "Flax N", hex: "#F0F0F0" },
      { name: "Ash Gray N", hex: "#DBDBDB" },
      { name: "Glaucous N", hex: "#BDBDBD" },
      { name: "Space Cadet N", hex: "#474747" },
      { name: "Lavender (web) N", hex: "#FFFFFF" },
      { name: "Dim Gray N", hex: "#737373" },
      { name: "Violet (JTC) N", hex: "#6B6B6B" }
    ],
    value4: [
      { name: "Pink Lavender V4", hex: "#c5a0b8" },
      { name: "Magenta Dye V4", hex: "#c5367d" },
      { name: "Van Dyke V4", hex: "#c59f93" },
      { name: "Flax V4", hex: "#c5c47d" },
      { name: "Ash Gray V4", hex: "#abc5b5" },
      { name: "Glaucous V4", hex: "#7186c5" },
      { name: "Space Cadet V4", hex: "#6573c5" },
      { name: "Lavender (web) V4", hex: "#b7bac5" },
      { name: "Dim Gray V4", hex: "#c5bfbd" },
      { name: "Violet (JTC) V4", hex: "#c577c2" }
    ],
    value3: [
      { name: "Pink Lavender V3", hex: "#94788a" },
      { name: "Magenta Dye V3", hex: "#94285e" },
      { name: "Van Dyke V3", hex: "#94776e" },
      { name: "Flax V3", hex: "#94935e" },
      { name: "Ash Gray V3", hex: "#809488" },
      { name: "Glaucous V3", hex: "#546494" },
      { name: "Space Cadet V3", hex: "#4c5694" },
      { name: "Lavender (web) V3", hex: "#898b94" },
      { name: "Dim Gray V3", hex: "#948f8e" },
      { name: "Violet (JTC) V3", hex: "#945991" }
    ],
    value2: [
      { name: "Pink Lavender V2", hex: "#62505c" },
      { name: "Magenta Dye V2", hex: "#621b3e" },
      { name: "Van Dyke V2", hex: "#624f49" },
      { name: "Flax V2", hex: "#62623e" },
      { name: "Ash Gray V2", hex: "#55625a" },
      { name: "Glaucous V2", hex: "#384362" },
      { name: "Space Cadet V2", hex: "#323962" },
      { name: "Lavender (web) V2", hex: "#5b5d62" },
      { name: "Dim Gray V2", hex: "#625f5e" },
      { name: "Violet (JTC) V2", hex: "#623b61" }
    ],
    value1: [
      { name: "Pink Lavender V1", hex: "#31282e" },
      { name: "Magenta Dye V1", hex: "#310d1f" },
      { name: "Van Dyke V1", hex: "#312724" },
      { name: "Flax V1", hex: "#31311f" },
      { name: "Ash Gray V1", hex: "#2a312d" },
      { name: "Glaucous V1", hex: "#1c2131" },
      { name: "Space Cadet V1", hex: "#191c31" },
      { name: "Lavender (web) V1", hex: "#2d2e31" },
      { name: "Dim Gray V1", hex: "#312f2f" },
      { name: "Violet (JTC) V1", hex: "#311d30" }
    ],
    value0: [
      { name: "Pink Lavender B", hex: "#181417" },
      { name: "Magenta Dye B", hex: "#18060f" },
      { name: "Van Dyke B", hex: "#181312" },
      { name: "Flax B", hex: "#18180f" },
      { name: "Ash Gray B", hex: "#151816" },
      { name: "Glaucous B", hex: "#0e1018" },
      { name: "Space Cadet B", hex: "#0c0e18" },
      { name: "Lavender (web) B", hex: "#161718" },
      { name: "Dim Gray B", hex: "#181717" },
      { name: "Violet (JTC) B", hex: "#180e18" }
    ],
  }
};

export default COLOR_LIBRARY;

