const long_pants = [
  "/assets/model/long_pants/long_pants (1).gltf",
  "/assets/model/long_pants/long_pants (2).gltf",
  "/assets/model/long_pants/long_pants (3).gltf",
  "/assets/model/long_pants/long_pants (4).gltf",
  "/assets/model/long_pants/long_pants (5).gltf",
  "/assets/model/long_pants/long_pants (6).gltf",
  "/assets/model/long_pants/long_pants (7).gltf",
  "/assets/model/long_pants/long_pants (8).gltf",
  "/assets/model/long_pants/long_pants (9).gltf",
  "/assets/model/long_pants/long_pants (10).gltf",
  "/assets/model/long_pants/long_pants (11).gltf",
  "/assets/model/long_pants/long_pants (12).gltf",
  "/assets/model/long_pants/long_pants (13).gltf",
  "/assets/model/long_pants/long_pants (14).gltf",
  "/assets/model/long_pants/long_pants (15).gltf",
  "/assets/model/long_pants/long_pants (16).gltf",
  "/assets/model/long_pants/long_pants (17).gltf",
  "/assets/model/long_pants/long_pants (18).gltf",
  "/assets/model/long_pants/long_pants (19).gltf",
  "/assets/model/long_pants/long_pants (20).gltf",
  "/assets/model/long_pants/long_pants (21).gltf",
];
